### ISSUE TITLE
Normalize dates of incoming data

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-transform#152]
Broken out from https://github.com/sul-dlss/dlme/issues/57.

![2019 Q4 DLME and Sinopia Work Cycle kickoff pptx](https://user-images.githubusercontent.com/37662787/65276860-ae254980-daf6-11e9-83ae-3a3185705b25.png)

Tickets have been written for each data provider. Prior to addressing collection level tickets, these issues need to be resolved:
- [x] Determine date form needed: https://github.com/sul-dlss/dlme/issues/551: needs multi value array with negative numbers as BCE dates.
- [ ] Design date view: https://github.com/sul-dlss/dlme/issues/546
- [ ] Modify intermediate representation to support earliest and latest dates?: https://github.com/sul-dlss/dlme-transform/issues/179
- [ ] Write general date normalization macros: https://github.com/sul-dlss/dlme-transform/issues/175
- [ ] Adjust data model to support Hijri dates: https://github.com/sul-dlss/dlme-transform/issues/190
- [ ] Hijri to Gregorian conversion and vice versa: https://github.com/sul-dlss/dlme-transform/issues/189

Once these general requirements are met, the collection level tickets can be addressed.

**Comment by jcoyne** [comment]
Please add examples of specific cases we need to handle.
E.g. When importing a Penn dataset and I see a date like "13-12-11" that should be represented in ISO 8601 as "2013-12-11"

**Comment by jacobthill** [comment]
Examples:

- Dates the come in as year or year range (e.g. 1304 - 1317, 1980/81, 1934/1934, -1820 - -1730, 383-395 AD, etc.) should be normalized to YYYY and YYYY-YYYY respectively.

- Dates that come in as day, month, year or month, day, year should be normalized to YYYY-MM-DD.

- Dates that come is as centuries (e.g. 16th c., 16. yüzyıl, etc.) should be normalized to the years of the century e.g. YYYY-YYYY.

For specific examples of incoming date values, look at the `Date` facet in [stage](https://spotlight.stage.dlmenetwork.org/library).

I think it will be impossible to write and maintain one algorithm to anticipate all incoming values and map them correctly. It probably makes more sense to write institution-level algorithms like we do for the config files. In the case that institutions adhere to a standard we can write standard-level algorithms.

**Comment by jcoyne** [comment]
@jacobthill That's a good start, but you need to be even more specific.  It looks like you want to represent date ranges as well as dates.  How should they be indexed?   Is that two values (upper and lower), or one values (a range) or multiple values (e.g. 1982/85 => [1982, 1983, 1984, 1985]) or a string value (ISO 8601 or EDTF)

What about precision? Are we okay adding artificial precision?  e.g. 1982 => 1982-01-01?  I believe solr dates are instants in time with millisecond precision, so if we decide the format is a solr date, bear that in mind.

I'd like *very* specific limited examples that we can use to see that we've completed the requirement:
For example:
* 1304 - 1317 => 1304-01-01 to 1317-01-01
* 1980/81 => 1980-01-01 to 1981-01-01
* 1934/1934 = 1934-01-01 to 1934-01-01
* 16th c. => 1500-1599
* 16 c. => 1500-1599
* 16TH c. => 1500-1599
* sixteenth c. => 1500-1599
* sixteenth century => 1500-1599
* sixteenth century AD => 1500-1599
* sixteenth century CE => 1500-1599

I have no idea what " 16. yüzyıl" means, so can you lay out all the possibilities for me?

**Comment by jacobthill** [comment]
- ca. late 19th century or early 20th century => 1850-1950
- 1880; 1881; 1882; 1883; 1884; 1885; 1886; 1887; 1888; 1889; 1890; 1891; 1892; 1893; 1894; 1895; 1896; 1897; 1898; 1899; 1900; 1901; 1902; 1903; 1904; 1905; 1906; 1907; 1908; 1909; 1910; 1911; 1912; 1913; 1914; 1915; 1916; 1917; 1918; 1919; 1920 => 1880-1920
- 300-499 AD => 300-499
- ca. 9th century B.C. => -900--801
- 1826/1826 => 1826
- ca. late 3rd–early 2nd millennium B.C. -2500--1500
- YE
654 - 655 => 654-655
- 1870s => 1870-1879
- 1965-1967? => 1965-1967
- 19. yüzyıl => 1800-1899 (yüzyıl means century in Turkish)
- K-II or Islamic I => ignore periods or consider using [periodo](https://perio.do/en/)
- -1000 - -1
n.d.a. => -1000--1
[n.d.], undated => don't map 
SH
1919 - 1920 => 1919-1920
post 14th century => ??? Can we do a beginning date without an end?

- 9th or 10th century AD /3rd or 4th century Hijri => 800-999

- "1991." => 1991

- 1220 CE => 1220
- 18. yüzyıl sonu => 1750-1799 (yüzyıl sonu means end of century in Turkish)
- 14-- => 1400-1499
- 17--? => 1700-1799
- [1939]. => 1939
- ca. 57–38 B.C. => -57--38
- between 1725 and 1825? => 1725-1825
- 1307 [1889 or 1890] => 1889-1890
- 1351 H (1932 M) => 1932 (H is for Hijri (the Islamic calendar) M is for Miladi (Arabic word for Gregorian calendar)
- 15. yüzyıl sonu veya 16. yüzyıl başı => 1451-1550
- 19. yüzyıl başları 1800-1849
- 19.12.1996 => 1996/12/19
- 19. yüzyıl ortası => 1825-1874
- 200905 => 2009/05
- 16--?-17--? => 1600-1799
- 1950 (?) => 1950
- 10[..] CE => 1000-1099
- 1230—1239 CE => 1230-1239

**Comment by jacobthill** [comment]
@jcoyne this list is not exhaustive. I went through all dates currently in stage but every dataset brings new possibilities. I noticed a few of the datasets were particularly challenging:

- Penn Museum: has lots of strings that represent periods
- Sakip Sabanci Museum: Has Turkish text
- American Numismatic Society: has dates in different calendar systems

I am going to see what I can to to clean up these values during mapping before the work cycle.

**Comment by jacobthill** [comment]
![date-normalization](https://user-images.githubusercontent.com/37662787/61815688-d0615a80-ae18-11e9-9236-6b2ccf4d5487.png)

### AIMS
Consistent output (Wed, 06 Jun 2018 09:12:39 +0000: 1). The metadata is from an iTunes podcast RSS feed.

### American Numismatic Society
-7661 of 7748 records have the cho_date value
-fairly consistent 1-4 digit year or year range (e.g. ddd or dddd-dddd)
-in multiple calendar systems, look into reharvesting (has consistent date ranges on website in Gregorian)

### AUB
-16480 of 16480 records have the cho_date value
-176 records have year ranges in the form dddd-dddd, the rest have dddd values
-still adding records so the above will change

### AUC 
-5094 of 5141 records have the cho_date value
-most commonly in the form "1947-11-28"
-strategy:
	-look for regex dddd-dd-dd; pass through
	-look for regex dddd (only); pass through (maybe add "-01-01")
	-look for regex ddd (only); pass through (maybe add leading "0" and trailing "-01-01")
	-look for regex dddd-dddd; pass through as year range
	-look for regex ddd-ddd; pass through as year range
	- gsub('ca. ', '') 
	-look for dddds => ddd(+1)d and drop s
	-look for dddd; dddd; dddd; etc., split on ';' and grab first (append'-' and last)

### BnF
-244 of 338 records have the cho_date value
-mostly in the form dddd but some in form dddd-dddd and one in form dd--

### Cambridge
-22300 of 22308 records have the cho_date value
-have not_before, not_after, and calendar as attributes and values
-format is "0500-01-01" but sometimes only the year e.g. "0800" is available "01-01" is always the month and day when available. 
-has string as element text

### Harvard
-651 of 813 records have the cho_date value
-some files have 3 different date values
-most common form is dddd, but also dddd-dddd, dduu, dddd [dddd]. etc.
-map dates with common pattern, ignore the rest

### Met
-6175 of 6175 records have the cho_date value
-always a year range (often B.C.)
-years can range from 1-4 digits

### Palestine Poster Project Archive
-12920 of 12920 records have the cho_date value
-all four digit years (dddd)

### Penn

### Princeton
-3230 of 3240 records have the cho_date value
-most are in the form dddd or dddd-dddd
-one record was "1749 January 5"

### Qatar National Library
-16132 of 16132 records have the cho_date value
-all in the form dddd/dddd

### Sakip Sabanci Museum
-1800 of 3438 records have the cho_date value
-many variations, suggest partial cleanup and ignore dates that are not easily matched to a pattern

**Comment by jcoyne** [comment]
@jacobthill what is the form needed in the app?

**Comment by jacobthill** [comment]
@jcoyne I think that might be a question for the access team. I'm not sure. We haven't decided what type of filter we will apply to dates and I'm also not sure what form will be needed to drive that filter once it is decided.

**Comment by jcoyne** [comment]
It seems like we should have some idea of the target before we get started, or we may end up with more code than we need, or the wrong code.

**Comment by jacobthill** [comment]
Agreed. @ggeisler let me know once you have some ideas on how to provide filters for the dates or if you want to consult more on this. Once this is decided, we should be able to determine the form the dates need to be in.n

**Comment by ggeisler** [comment]
Based on separate discussions with @jacobthill and @cbeer, here's a general summary of what we are proposing:

- The source date value from incoming records is maintained as is and will be used for display purposes only(e.g. _Source date_, probably just on the item show page, to serve as additional context for the user).
- The source date value is transformed/normalized to a new date field (_Date_) that will be indexed and used for searching, facets, and sorting.
- Source date values are normalized to year format `yyyy` in the Gregorian calendar (I'm not sure how you indicate whether the year is BCE or not with that format), even though that will sometimes mean losing precision (but the user will still be able to see the original, more precise date on the item show page, in the _Source date_ field).
- The format of the new _Date_ field is an array. If the source date is contained within a single year it's something like `[yyyy]`; if the source date is a range or encompasses multiple years it's `[yyyy, yyyy, yyyy]`

**Comment by jacobthill** [comment]
Something that occurred to me after our last meeting @ggeisler is that the normalized form may need to be stored in two values e.g. instead of 'date' use 'start_date' and 'end_date'. This would make the traject mapping work easier. Sometimes the dates come in as start and end dates and mapping two fields to one might be challenging.

**Comment by ggeisler** [comment]
@jacobthill I don't really know anything about traject, but if I understood correctly from my discussion with @cbeer when you have a start_date (e.g., 1910) and an end_date (1915) you would just interpolate the years in the range between the start_date and the end_date: `[1910, 1911, 1912, 1913, 1914, 1915]`

This gets beyond what I'm qualified to talk about, but my understanding is in our other apps where this comes up we just use the single date field; I'm not sure how well our usual approaches to indexing work when you have two date fields to take into account.  

I am pretty sure we don't want to expose two distinct date fields ('start_date' and 'end_date') to the user in the UI (not that you were necessarily suggesting that).

**Comment by jacobthill** [comment]
We don't want to expose two values to the end user, of course. The question I have is how to use traject to map two values in the source data (a start date and an end date) to one field in the Intermediate Representation (IR). I assume it can be done and if that's what needs to be done, the infrastructure team can help me figure it out. What I'm wondering is that if we gave the access team a start_date and an end_date could they generate the array or does in need to be stored in the IR? @cbeer Can you help us all get on the same page?

**Comment by jacobthill** [comment]
Also, one other clarification question. Can the array store negative values to represent BCE years?

**Comment by cbeer** [comment]
> e.g. instead of 'date' use 'start_date' and 'end_date'

That works up until you have non-continuous ranges (1930-1933, and 1965). It'll be much easier and consistent across a variety of  use cases (and will work better with our existing tooling) if we have only a single date/year field with multiple values. This is the approach we've taken in searchworks and elsewhere and seems to work just fine, so I'm not sure why we'd go out of our way to invent another representation.

**Comment by jacobthill** [comment]
Got it, I'll get the infrastructure team to help me figure out how to map two values to one field.

**Comment by aaron-collier** [comment]
Individual tickets are captured and ready. Closing this issue.
