### ISSUE TITLE
refactor date_parsing macros to use functionality in parse_date gem

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dlme-transform#291]
the parse_date gem issues:

- [x] https://github.com/sul-dlss/parse_date/issues/8 (`ParseDate.year_range_valid?`)
- [x] https://github.com/sul-dlss/parse_date/issues/9 (`ParseDate.range_array`)
- [x] https://github.com/sul-dlss/parse_date/issues/10 (`ParseDate.parse_range`)

will put more of the date parsing code into the parse_date gem, where it can be used by other code bases.   We will want to refactor the date_parsing macros here to utilize the methods in parse_date gem, slimming down the code here in dlme-transform and getting more parsing functionality in the bargain.

This will require a new release of the parse date gem once all three issues above have been merged to parse_date repo's master branch.

refactor:
- [x] update to use parse_date gem version with changes (v0.3.1)
- [x] refactor/replace `range_array_from_positive_4digits_hyphen` 
- [x] refactor/replace `single_year_from_string` 
- [x] refactor/replace `year_array`

**Comment by ndushay** [comment]
refactor:
- [ ] update to use parse_date gem version with changes (v0.3.1)
- [ ] refactor/replace `range_array_from_positive_4digits_hyphen` 
- [ ] refactor/replace `single_year_from_string` 
- [ ] refactor/replace `year_array`
